import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { fetchData } from "@/utils/fetch";
import { CardType } from "@/types/type";
import CategoryCard from "@/component/CategoryCard";
import Layout from "@/component/Layout";

const inter = Inter({ subsets: ["latin"] });

type PropsType = {
  data: CardType[];
};
export default function Home(props: PropsType) {
  // const data = fetchData("categories/");
  // console.log(data);
  // console.log(props);
  return (
    <Layout icon={false}>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          {props.data.map((data) => {
            return <CategoryCard key={data.id} data={data} path="category" />;
          })}
        </main>
      </>
    </Layout>
  );
}

export async function getStaticProps() {
  const dataCategories = await fetchData("categories/");
  const data = dataCategories.map((d: any) => {
    return { id: d.id, name: d.category, image: d.thumbnail };
  });
  return {
    props: {
      // dataCategories: dataCategories,
      data,
    },
  };
}
